Portfolio: setup and Mobile version skeleton
TekyRey/Portfolio pull request #1
Opened 2022-05-25 13:13 UTC by TekyRey

### **Setup and Mobile version skeleton**
In this module i:

- Created a nav section
- added a background image
- added an introduction section
- added a social media links section

2022-05-25 15:27 UTC, omar-muhamad requested changes
# Changes Required ♻️
### Hi @TekyRey,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-25 15:27 UTC, omar-muhamad commented on index.html
> +        </div>
- [ ] Nice work wrapping the site logo inside an `<a>` tag but kindly for semantic reasons the `<div>` and `<p>` tags and leave the `<a>` tag directly in the `<nav>`.

2022-05-25 15:27 UTC, omar-muhamad commented on index.html
> +        </div>
- [ ] Same here kindly put the `<button>` tag directly on the nav and remove this wrapping `div`.

2022-05-25 15:27 UTC, omar-muhamad commented on index.html
> +              </div>
- [ ] For the social icons Please use a `<ul>` tag to group them, `<li>` per icon, and each icon has a `<a>` link tag.
for example: 
```
<ul>
   <li>
       <a href="your soical link path here">put the Icon here</a>
   </li>
    ....................
    .....................
</ul>
```

2022-05-25 15:27 UTC, omar-muhamad commented on style.css
> +}
- [ ] For header styling Kindly make the hamburger button aligned beside the logo but on the right like the given Figma design.
- [ ] Please add the correct margin-top value for the header by decreasing it a little bit. and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/170299559-eb7a6dbb-33ef-4015-8411-3f9356d40aec.png)  | ![image](https://user-images.githubusercontent.com/68796232/170299521-e0987c3a-4d0e-4847-8413-017d642b94ab.png) |

2022-05-26 08:24 UTC, topeogunleye approved these changes
### Hi @TekyRey, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 08:39 UTC, merged